name: "Build Matrix"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, synchronize , reopened ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'dependabot')
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: Make sure it builds.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
        env:
          GATSBY_API_KEY: ${{ secrets.GATSBY_API_KEY }}
          GATSBY_G_MAPS: ${{ secrets.GATSBY_G_MAPS }}
