name: "Update dependencies [scheduled]"
on:
  schedule:
    - cron: '0 8 * * 4' # every thursday @ AM 8:00
jobs:
  npm_update_sync:
    runs-on: ubuntu-latest
    name: Update npm packages and sync package.json with nodejs 16 npm 7
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update package.json
        id: update
        uses: tjololo/npm-package-update-sync@v1
        with:
          comment-updated: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          body: ${{ steps.update.outputs.body }}
          branch: updates/bump-versions
          commit-message: ":books: updated npm dependencies"
          delete-branch: true
          labels: dependencies
          title: ":books: updated npm dependencies"
